name: Spell Check PR

on:
  # pull_request:
  #   types: [opened, edited, synchronize]
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Extract PR content and commit messages

    - name: Invoke AWS Lambda by OIDC
      uses: y5347M/invoke-aws-lambda-oidc@v1
      with:
        aws-region: 'eu-central-1'
        role-to-assume: 'arn:aws:iam::245859492604:user/test-spell-check'
        function-name: 'spellcheck-lambda'
        payload: '{"content":"This is a spelling exampl"}'

    - name: Output Lambda Response
      run: echo "Lambda Response: ${{ steps.invoke.outputs.lambda-invoke-response }}"
