name: Spell Check

on:
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - '**/*.md'
      - '**/*.txt'
      - '**/*.tf'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Install codespell
      - name: Install codespell
        run: |
          sudo apt-get update
          sudo apt-get install -y codespell

      # Step 3: Run codespell on changed files
      - name: Check spelling in PR changes
        run: |
          # List files changed in this PR
          git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} > changed_files.txt

          # Check spelling errors in changed files
          cat changed_files.txt | xargs codespell --skip="*.json,*.min.js,*.png" --check-filenames --check-hidden -q 3
